name: Push to GHCR

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5
        with:
          strip_tag_prefix: 'v'
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.11.0 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.branch-name.outputs.tag }}
